### ISSUE TITLE
Any plans to update plugin so the accessory state is changed when teams status changes?

### ISSUE THREAD

**Issue by kenwebster** [estruyf/homebridge-presence-switch-msgraph#4] opened 2020-10-21 17:25 UTC
Great plugin! I have a light right outside the office door that is multi-color, thinking about changing the busy light to the bulb above the door(red = busy, etc). Any plans to add the ability to update the sensor switch for the teams status grabber so we can automate other accessories to its state? 

Thanks!

**Comment by estruyf** [comment] 2020-10-22 11:58
That could be indeed a great enhancement. Will try to find time in order to implement it.

**Comment by benfysh** [comment] 2020-10-27 13:43
Second this request, I have a hue bulb outside my office that I would like to use for status and whilst the busylight API looks similar to the hue one I am not technically adept enough to adapt it! If the state is updated then I should be able to use HomeKit automation to achieve what I want. Thanks :)

**Comment by estruyf** [comment] 2020-10-28 11:23
Worked a bit on a switch yesterday, but it seems that `HomeKit` only supports two states for switches `on`/`off`. I can of course create it as something else, like a `lightbulb` and change the brightness. Available `100%`, Away `75%`, Busy `50%`, and Offline `0%`. Not sure if this would work for the automation part.

Let me know your thoughts and if you want to test it out, there is a beta version for `1.3.0` available. If you have a good plugin as an example or which you are using, let me know.

**Comment by benfysh** [comment] 2020-10-28 18:50
It looks like you can only trigger automations based on something being either on or off so I don't think % brightness would work. 

I guess the only workaround would be a switch per teams status, I appreciate that this might be more work! 

Will take a look at the beta what does the 'on' state signify? Thanks

**Comment by estruyf** [comment] 2020-10-29 19:10
The `on` state currently is for starting the Microsoft Graph calls. When it is off, it doesn’t do polling. It’s also used as sort of reset trigger for re-authenticating.

Still looking at other solutions how they approach it. Three buttons would be possible, but don’t think this makes it easier to automate. I’m going to test a bit more.

**Comment by benfysh** [comment] 2020-10-29 20:31
The eve app does allow you to set up automations based on brightness level of a light. ![image](https://user-images.githubusercontent.com/404201/97629208-ad632480-1a25-11eb-8250-d6ee8945f5e2.jpeg)

So this could work as you don't need any eve devices to use it.

**Comment by estruyf** [comment] 2020-10-29 20:55
Just created a new update (beta) that is rolling out. I have created sub-switches.

![IMG_2638](https://user-images.githubusercontent.com/2900833/97631499-5fecb480-1a31-11eb-8721-deb1ca3e4a02.jpg)

![IMG_2639](https://user-images.githubusercontent.com/2900833/97631513-6549ff00-1a31-11eb-960b-580034f1e09a.PNG)

There are 4 states switches:

- Offline
- Away
- Busy
- Available

Let me know if this works for you.

**Comment by benfysh** [comment] 2020-10-30 10:09
Seems to be working well thanks. Would it be possible to add do not disturb also as this usually indicates I am presenting? Also could the busy light elements of the config now be optional? Thanks again :)

**Comment by estruyf** [comment] 2020-10-30 16:26
New beta version is building atm. It contains the Do Not Disturb switch + the `setColorApi`, `offApi`, and `onApi` options are now optional.

**Comment by benfysh** [comment] 2020-10-31 14:40
Probably a problem at my end but I am not seeing the Do Not Disturb switch. 

I have managed to exclude the API elements manually in the config file and am no longer getting the warning about the API being available in the logs. The plugin setting screen still shows these elements as mandatory by the way.

**Comment by estruyf** [comment] 2020-10-31 20:17
My mistake, seems I accidentally removes some code before committing it. Should have been fixed now.

**Comment by benfysh** [comment] 2020-10-31 21:18
Tested and confirmed as working. Thanks again for adapting this plugin with this functionality :)

**Comment by estruyf** [comment] 2020-10-31 22:47
Thank you for suggesting the enhancement. I’ll publish the new release in the next days.

**Comment by estruyf** [comment] 2020-11-01 19:42
Closing this as version `1.3.0` has now been released. Thanks again for suggesting the enhancement.

**Closed by estruyf** 2020-11-01 19:42 UTC
Labels: enhancement
